// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *globalnav → menu items*
 */
export interface GlobalnavDocumentDataMenuItemsItem {
  /**
   * label field in *globalnav → menu items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globalnav.menu_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for globalnav documents
 */
interface GlobalnavDocumentData {
  /**
   * menu items field in *globalnav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globalnav.menu_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_items: prismic.GroupField<Simplify<GlobalnavDocumentDataMenuItemsItem>>;
}

/**
 * globalnav document from Prismic
 *
 * - **API ID**: `globalnav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalnavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalnavDocumentData>,
    "globalnav",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | FeatureProjectSlice
  | OneSlice
  | ClientsSlice
  | HomeHeaderSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = GlobalnavDocument | HomeDocument;

/**
 * Item in *Clients → Default → Primary → clientRoster*
 */
export interface ClientsSliceDefaultPrimaryClientRosterItem {
  /**
   * image field in *Clients → Default → Primary → clientRoster*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clientRoster[].client
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  client: prismic.ImageField<never>;
}

/**
 * Primary content in *Clients → Default → Primary*
 */
export interface ClientsSliceDefaultPrimary {
  /**
   * bgImage field in *Clients → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.bgImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgImage: prismic.ImageField<never>;

  /**
   * clientRoster field in *Clients → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clientRoster[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  clientRoster: prismic.GroupField<
    Simplify<ClientsSliceDefaultPrimaryClientRosterItem>
  >;
}

/**
 * Default variation for Clients Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClientsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Clients*
 */
type ClientsSliceVariation = ClientsSliceDefault;

/**
 * Clients Shared Slice
 *
 * - **API ID**: `clients`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSlice = prismic.SharedSlice<
  "clients",
  ClientsSliceVariation
>;

/**
 * Primary content in *FeatureProject → Default → Primary*
 */
export interface FeatureProjectSliceDefaultPrimary {
  /**
   * image field in *FeatureProject → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_project.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * image2 field in *FeatureProject → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_project.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;
}

/**
 * Default variation for FeatureProject Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureProject*
 */
type FeatureProjectSliceVariation = FeatureProjectSliceDefault;

/**
 * FeatureProject Shared Slice
 *
 * - **API ID**: `feature_project`
 * - **Description**: FeatureProject
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureProjectSlice = prismic.SharedSlice<
  "feature_project",
  FeatureProjectSliceVariation
>;

/**
 * Item in *HomeHeader → Default → Primary → images*
 */
export interface HomeHeaderSliceDefaultPrimaryImagesItem {
  /**
   * image field in *HomeHeader → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_header.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeHeader → Default → Primary*
 */
export interface HomeHeaderSliceDefaultPrimary {
  /**
   * Header field in *HomeHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_header.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * images field in *HomeHeader → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_header.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<HomeHeaderSliceDefaultPrimaryImagesItem>>;

  /**
   * bgImage field in *HomeHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_header.default.primary.bgImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgImage: prismic.ImageField<never>;

  /**
   * buttonImage field in *HomeHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_header.default.primary.buttonImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  buttonImage: prismic.ImageField<never>;
}

/**
 * Default variation for HomeHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHeader*
 */
type HomeHeaderSliceVariation = HomeHeaderSliceDefault;

/**
 * HomeHeader Shared Slice
 *
 * - **API ID**: `home_header`
 * - **Description**: HomeHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeaderSlice = prismic.SharedSlice<
  "home_header",
  HomeHeaderSliceVariation
>;

/**
 * Item in *Omega → Default → Primary → copy*
 */
export interface OneSliceDefaultPrimaryCopyItem {
  /**
   * bullet1 field in *Omega → Default → Primary → copy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.copy[].bullet1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet1: prismic.KeyTextField;

  /**
   * bullet2 field in *Omega → Default → Primary → copy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.copy[].bullet2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet2: prismic.KeyTextField;

  /**
   * bullet3 field in *Omega → Default → Primary → copy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.copy[].bullet3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet3: prismic.KeyTextField;
}

/**
 * Primary content in *Omega → Default → Primary*
 */
export interface OneSliceDefaultPrimary {
  /**
   * image1 field in *Omega → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * projectfeature1 field in *Omega → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.projectfeature1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  projectfeature1: prismic.ImageField<never>;

  /**
   * projectfeature2 field in *Omega → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.projectfeature2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  projectfeature2: prismic.ImageField<never>;

  /**
   * Header field in *Omega → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * copy field in *Omega → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.copy[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  copy: prismic.GroupField<Simplify<OneSliceDefaultPrimaryCopyItem>>;

  /**
   * ViewCaseStudy field in *Omega → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.viewcasestudy
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  viewcasestudy: prismic.KeyTextField;

  /**
   * arrow field in *Omega → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: one.default.primary.arrow
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  arrow: prismic.ImageField<never>;
}

/**
 * Default variation for Omega Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OneSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OneSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Omega*
 */
type OneSliceVariation = OneSliceDefault;

/**
 * Omega Shared Slice
 *
 * - **API ID**: `one`
 * - **Description**: One
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OneSlice = prismic.SharedSlice<"one", OneSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GlobalnavDocument,
      GlobalnavDocumentData,
      GlobalnavDocumentDataMenuItemsItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      ClientsSlice,
      ClientsSliceDefaultPrimaryClientRosterItem,
      ClientsSliceDefaultPrimary,
      ClientsSliceVariation,
      ClientsSliceDefault,
      FeatureProjectSlice,
      FeatureProjectSliceDefaultPrimary,
      FeatureProjectSliceVariation,
      FeatureProjectSliceDefault,
      HomeHeaderSlice,
      HomeHeaderSliceDefaultPrimaryImagesItem,
      HomeHeaderSliceDefaultPrimary,
      HomeHeaderSliceVariation,
      HomeHeaderSliceDefault,
      OneSlice,
      OneSliceDefaultPrimaryCopyItem,
      OneSliceDefaultPrimary,
      OneSliceVariation,
      OneSliceDefault,
    };
  }
}
