// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  global_menu: dynamic(() => import("./GlobalMenu")),
  home_header: dynamic(() => import("./HomeHeader")),
};
