// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  clients: dynamic(() => import("./Clients")),
  feature_project: dynamic(() => import("./FeatureProject")),
  home_header: dynamic(() => import("./HomeHeader")),
  one: dynamic(() => import("./Omega")),
};
